[project]
name = "backblaze-file-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "b2sdk>=2.8.0",
    "pylint>=3.3.5",
]
